// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKdsxFyR3Y7BJK6KLQpHu8m63v_mA3PHQ',
    appId: '1:20175498883:web:5840648411022afd0035b6',
    messagingSenderId: '20175498883',
    projectId: 'tech-torrent',
    authDomain: 'tech-torrent.firebaseapp.com',
    storageBucket: 'tech-torrent.appspot.com',
    measurementId: 'G-0NLVDKC0C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9UO2oL8ytxsMYHl3zmp4EkQDJZZ6THGU',
    appId: '1:20175498883:android:9c3da177d291c14c0035b6',
    messagingSenderId: '20175498883',
    projectId: 'tech-torrent',
    storageBucket: 'tech-torrent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP_gTMXrRhE-HMwdXUTqrcQLTRwtJbNBg',
    appId: '1:20175498883:ios:485fd3b7c60615cb0035b6',
    messagingSenderId: '20175498883',
    projectId: 'tech-torrent',
    storageBucket: 'tech-torrent.appspot.com',
    iosClientId: '20175498883-l1mhv5qj8cmmg7p7h749tc4nq18mharo.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP_gTMXrRhE-HMwdXUTqrcQLTRwtJbNBg',
    appId: '1:20175498883:ios:485fd3b7c60615cb0035b6',
    messagingSenderId: '20175498883',
    projectId: 'tech-torrent',
    storageBucket: 'tech-torrent.appspot.com',
    iosClientId: '20175498883-l1mhv5qj8cmmg7p7h749tc4nq18mharo.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
